=pod

=encoding UTF-8

=head1 NAME

CellBIS::DBI - Database Interface to use CellBIS Web Framework.

=head1 SYNOPSIS

    use CellBIS::DBI;

    # Hashref database config :
    my $dbconfig = {
        'db_host' => 'localhost',
        'db_name' => 'your_db',
        'db_user' => 'your_userdb',
        'db_psas' => 'your_passUserDb'
    };

    # Initialization (example mysql) :
    my $dbh = CellBIS::DBI->mysql($dbconfig);

    # For Disconnected :
    $dbh->disconnect();

If you want use PostgreSQL, use same method for MySQL. And if you want use SQLite,
no database config, but location of file database SQLite.

=head1 DESCRIPTION

This module is standard Database Interface based DBI to used in CellBIS Web Framework.

=head1 EXPLAIN Subroutine mysql

    Description Subroutine :
    ----------------------------------------
    Subroutine for MySQL Database.

    Parameter Subroutine :
    ----------------------------------------
    $db_cfg         =>  Hashref Database config.

=head1 EXPLAIN Subroutine pgsql

	Deskripsi subroutine pgsql() :
	----------------------------------------
	Subroutne for PostgreSQL Database.

	Parameter subroutine pgsql() :
	----------------------------------------
	$db_cfg         =>  Hashref Database config.

=head1 EXPLAIN Subroutine sqlite

    Description Subroutine :
    ----------------------------------------
    Subroutine for SQLite Database.

    Parameter Subroutine :
    ----------------------------------------
    $fieloc_db          =>  Location of File database SQLite.

=head1 SEE ALSO

L<DBI>

=head1 AUTHOR

Achmad Yusri Afandi, (yusrideb@cpan.org)

=head1 COPYRIGHT AND LICENSE

Copyright (c) 2016, Achmad Yusri Afandi, All Rights reserved.

This library is free software; you can redistribute it and/or modify it under the same terms as Perl itself.

=cut